CI: ensure manpages are installed in goreleaser.yml

diff --git a/.github/workflows/mandoc.yml b/.github/workflows/mandoc.yml
--- a/.github/workflows/mandoc.yml
+++ b/.github/workflows/mandoc.yml
@@ -4,10 +4,10 @@ on:
   push:
     branches:
     paths:
-      - '**.[1-9]'
+      - "**.[1-9]"
   pull_request:
     paths:
-      - '**.[1-9]'
+      - "**.[1-9]"
 
 jobs:
   build:
@@ -20,7 +20,7 @@ jobs:
         uses: actions/checkout@v4
 
       - name: install mandoc
-        run: sudo apt install -y mandoc
+        run: sudo apt install -y mandoc yq
 
       - name: lint
         run: |
@@ -30,3 +30,8 @@ jobs:
           cd "$dir"
           mandoc -Tlint -Wstyle -l *
           rm -rf "$dir"
+
+      - name: Ensure man pages are listed in .goreleaser.yml
+        run: |
+          diff <(find ./plakar.1 ./subcommands -name '*.1' | sort | xargs -L1 basename | sort) <(cat .goreleaser.yml | yq -r '.nfpms[0].contents[].src' | xargs -L1 basename | sort) || (echo ">> Missing man pages in .gotreleaser.yml for nfpms" && exit 1)
+          diff <(find ./plakar.1 ./subcommands -name '*.1' | sort | xargs -L1 basename | sort) <(cat .goreleaser.yml | yq -r '.homebrew_casks[].manpages[]' | xargs -L1 basename | sort) || (echo ">> Missing man pages in .gotreleaser.yml for homebrew_casks" && exit 1)
